### PR TITLE
Follow up: updateLiteralPaths to also fix specifiers if need be

### PR DESCRIPTION
**Pull request by snewcomer**
@dcyriller Sry :( Unable to commit to your branch.  Feel free to steal what is in here and modify as you see fit.

Ref #24

### CODE REVIEW

**Comment by dcyriller** [comment]
No worries, the codemod is not even released yet. And this is a great feature :)

You've been very fast. Hoping to review today.

**Comment by dcyriller** [comment]
I've added two commits to fix two other small issues. Does it sound good to you?

I've run this codemod's branch on a pretty large app. It sounds to run fine :)

Also, I'll ask for another review.

**Review by NullVoxPopuli — APPROVED** [review]
lgtm :+1:

**Comment by snewcomer** [comment]
Great additions!  This looks g2g

**Review by dcyriller — APPROVED** [review]

**Pull request merged**
